---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: esb-operationassetsinventory
  namespace: tibco-dev
spec:
  selector:
    matchLabels:
      app: esb-operationassetsinventory
  replicas: 1
  template:
    metadata:
      labels:
        app: esb-operationassetsinventory
        esb: tibco
    spec:
      containers:
      - name: esb-operationassetsinventory
        image: 548018587351.dkr.ecr.us-east-2.amazonaws.com/testing:2206131426
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthcheck/readiness
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 15
        livenessProbe:
          httpGet:
            path: /healthcheck/liveliness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 60
        envFrom:
        - configMapRef:
            name: dev-configmap-esb-operationassetsinventory
        - secretRef:
            name: dev-secret-esb-operationassetsinventory
        env:
        - name: HOST_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: tcp_self_url
          value: $(HOST_NAME):2551
        - name: ami_agent_url
          value: $(HOST_IP):2571
        volumeMounts:
          - name: pv-volume
            mountPath: "/mnt/data"
      volumes:
        - name: pv-volume
          persistentVolumeClaim:
            claimName: pv-claim
         
