apiVersion: v1
kind: Service
metadata:
  name: esb-operationassetsinventory-service
  namespace: tibco-prod
spec:
  selector:
    app: esb-operationassetsinventory
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8080
  type: ClusterIP
